### ISSUE TITLE
About memory leak

### ISSUE THREAD

**Issue by chikiuso** [rohit-gupta/Video2Language#3]
Hi Rohit, I got the following error msg when running the extract features, do you have any idea? Thanks!

Traceback (most recent call last):
  File "batched_extractor.py", line 147, in <module>
    encoded_frame_sequence = TimeDistributed(convnet_model)(video_input)
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 619, in __call__
  File "build/bdist.linux-x86_64/egg/keras/layers/wrappers.py", line 211, in call
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2085, in call
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2235, in run_internal_graph
  File "build/bdist.linux-x86_64/egg/keras/layers/normalization.py", line 193, in call
  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 1004, in moving_average_update
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 180, in _zero_debias
    "biased", initializer=biased_initializer, trainable=False)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/chikiuso/.conda/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 1004, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "build/bdist.linux-x86_64/egg/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)

swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

**Comment by rohit-gupta** [comment]
Hi @chikiuso, what version of Keras/Tensorflow are you using ? Based on some StackOverflow answers I think this might be because of a bug in Tensorflow Version 1.3

**Comment by chikiuso** [comment]
Thanks, solved :D
